name: Upload iOS to Test Flight

on:
  push:
    branches:
      - main

jobs:
  release-ios:
    name: Build and release iOS app
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '12.22.0'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.6'
      - name: Install Bundler
        run: gem install bundler:2.2.27
      - uses: actions/cache@v1
        id: cocoapods-cache
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
          ${{ runner.os }}-pods-
      - name: Cocoapods
        if: steps.cocoapods-cache.outputs.cache-hit != 'true'
        run: |
          bundle exec pod install
      - name: Install Fastlane
        run: bundle install
      - name: Install packages
        run: yarn install
      - uses: maierj/fastlane-action@v2.2.0
        with:
          lane: 'ios test_flight'
          subdirectory: 'ios'
        env:
          TEMP_KEYCHAIN_USER: ${{ secrets.TEMP_KEYCHAIN_USER }}
          TEMP_KEYCHAIN_PASSWORD: ${{ secrets.TEMP_KEYCHAIN_PASSWORD }}
          GIT_AUTHORIZATION: ${{ secrets.GIT_AUTHORIZATION }}
          APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
          APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
          APPLE_KEY_CONTENT: ${{ secrets.APPLE_KEY_CONTENT }}
          DEVELOPER_APP_ID: ${{ secrets.DEVELOPER_APP_ID }}
          PROVISIONING_PROFILE_SPECIFIER: ${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}
          DEVELOPER_APP_IDENTIFIER: ${{ secrets.DEVELOPER_APP_IDENTIFIER }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}